-- 创建配置表
CREATE TABLE IF NOT EXISTS ranking_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,       -- 配置键名 (e.g., 'filter_config')
    value JSONB NOT NULL DEFAULT '{}'::jsonb, -- 配置内容
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 添加注释
COMMENT ON TABLE ranking_config IS '排品系统配置表';
COMMENT ON COLUMN ranking_config.key IS '配置唯一标识键';
COMMENT ON COLUMN ranking_config.value IS 'JSON格式的配置数据';
